 -- ---------------- SQL Project - Zomato Sales Analysis ---------------------------------
 -- --------------------------------------------------------------------------------------
 use zomatodb;
 -- 1. List the top 3 customers who have placed the highest number of orders.
 select 
   customer.customer_id ,customer.customer_name, count(order_detail.order_id)  as Highest_No_Of_Order from
   customer
   join order_detail
   on customer.customer_id = order_detail.customer_id
group by  customer.customer_id
order by Highest_No_Of_Order desc limit 3;
   
-- 2.Find the restaurant that has received the highest average rating.

select  
restaurant_id, restaurant_name,avg(rrating) as Rating 
from restaurant
group by restaurant_id ,restaurant_name
 order by  Rating desc limit 1;
 
-- 3.List all orders from order_detail that were delivered in under 30 minutes.
select (order_id),customer_id,
order_time,delivered_time,
timestampdiff(minute, order_time, delivered_time) as delivery_time_in_minutes
from order_detail
where timestampdiff(minute, order_time, delivered_time) < 30;

-- 4. Calculate the total revenue generated by each food item. 
-- Display food_id, food_name and Total revenue ordered by total revenue in descending order.
  
  select foods.food_id,foods.food_name,
  sum(order_food.quantity * foods.price_per_unit) as Total_Revenue 
  from foods join
  order_food on foods.food_id = order_food.food_id
  group by food_id,food_name 
  order by Total_Revenue  desc ;
  
  -- 5. Find the second highest revenue-generating restaurant.
  use zomatodb;
with  RevenueCTE as (
select  restaurant.restaurant_id ,restaurant.restaurant_name,
sum(order_food.quantity * foods.price_per_unit) as Tatal_Revenue,
dense_rank() over( order by sum(order_food.quantity * foods.price_per_unit) 
desc) as revenue_rank
from restaurant
join  order_food 
on restaurant.restaurant_id =order_food.restaurant_id
join foods
on order_food.food_id = foods.food_id
group by restaurant.restaurant_id, restaurant.restaurant_name
)
select * from RevenueCTE
where revenue_rank = 2;

-- 6. Find the 5 most popular food items based on the quantity sold.
select 
    foods.food_id,foods.food_name,
    sum(order_food.quantity) as Total_Quantity_Sold
from foods
join order_food  on foods.food_id  = order_food.food_id
group by foods.food_id,foods.food_name
order by  Total_Quantity_Sold desc limit 5;

-- 7.List the top 3 Zomato employees with the highest average delivery ratings.
select employee_id,employee_name,
employee_avg_rating AS Avg_Rating
from zomato_employee
order by Avg_Rating desc limit 3;

-- 8. Determine the month with the highest number of total orders placed.
select extract(month from order_time) as month_number,
count(order_id) as total_order 
from order_detail
group by month_number
order by total_order desc limit 1;

-- 9. Calculate the average order amount for each customer. Order by average order amount in descending order.
select customer.customer_id,customer_name ,
avg(order_food.quantity * foods.price_per_unit) as Total_amount
 from customer
 join order_food on customer.customer_id = order_food.customer_id
 join foods  on order_food.food_id = foods.food_id
 group by customer.customer_id,customer_name 
 order by Total_amount desc ;
 
 -- 10.Identify the most frequent customer for each restaurant.
with Customer_Frequency as(
select  customer.customer_id,customer_name,restaurant.restaurant_name,
count(order_detail.restaurant_id )  as Most_Vist_Restaurant,
rank() over ( partition by restaurant.restaurant_name 
order by count(order_detail.restaurant_id ) desc ) as Restaurant_Rank
from customer
join order_detail on customer.customer_id = order_detail.customer_id
join restaurant  on order_detail.restaurant_id  = restaurant.restaurant_id 
group by customer.customer_id,customer_name,restaurant.restaurant_name 

)
select customer_name, restaurant_name  , Most_Vist_Restaurant from Customer_Frequency
  where Restaurant_Rank = 1;
  
  
  -- another query 
 --  select  customer.customer_id,customer_name,restaurant.restaurant_name,
--   count(order_detail.restaurant_id )  as Most_freq_coutomer_restaurant
--   from customer
--    join order_detail on customer.customer_id = order_detail.customer_id
--    join restaurant  on order_detail.restaurant_id  = restaurant.restaurant_id 
--    group by customer.customer_id,customer_name,restaurant.restaurant_name
--     order by  Most_freq_coutomer_restaurant desc limit 3 ;

-- 11.Calculate the total number of orders placed on weekends.

select 
dayname(order_time) as Day_name,
count(order_id) as total_order from order_detail
where dayofweek(order_time) in (1,7)
group by Day_Name ;

  
-- 12. Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends.
select case when 
 dayofweek(order_time) in (1,7)then 'weekend'
 else 'weekday' end as day_type,
 count(order_id) as total_orders,
 avg(timestampdiff(minute ,order_time, delivered_time)) as Avg_time
 from order_detail
 group by day_type ;



-- 13. List the top 5 most expensive food items. Display food_id, food_name, and price_per_unit for 
-- all food items with the highest 5 prices.
use zomatodb;
 -- select  food_id,food_name,price_per_unit as highest_price  from foods 
--  group by  food_id,food_name
--  order by price_per_unit desc limit 5;
--  
 -- ------- ----------
 -- update code
select 
    food_id,
    food_name,
    price_per_unit as highest_price,
    price_rank
from (
    select 
        food_id,
        food_name,
        price_per_unit,
        dense_rank() over (order by price_per_unit desc) as price_rank
    from foods
) as ranked_foods
where price_rank <= 5
order by highest_price desc;
 
 
-- 14. Find the restaurant with the most diverse menu (i.e., the highest number of food items).
select r.restaurant_id, r.restaurant_name,
 count(distinct (orf.food_id)) as diverse_menu
 from restaurant r
 join order_food orf on r.restaurant_id = orf.restaurant_id
 group by r.restaurant_id, r.restaurant_name
 order by  diverse_menu desc limit 1;
  
-- 15.Calculate total payment amount for each payment type.  
select p.payment_type ,p.payment_status,
count( distinct ofd.order_id) as Total_order,
sum(ofd.quantity * f.price_per_unit) as total_amount
from payment_table p 
join order_food ofd  on p.order_id = ofd.order_id
join foods f on ofd.food_id = f.food_id
group by p.payment_type ,p.payment_status
order by total_amount desc ;
